apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
- target:
    kind: ClusterIssuer
    group: cert-manager.io
    version: v1
    name: public-issuer
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /spec/acme/solvers/1/dns01/route53/accessKeyID
      value: '<AWS_ACCESS_KEY_ID>'

resources:
- aws.public.clusterissuer.yaml

secretGenerator:
- name: aws-creds
  namespace: openshift-operators
  envs:
    - aws.secret
