---

- name: Get facts for virtual network info
  azure.azcollection.azure_rm_virtualnetwork_info:
    resource_group: "{{ AKS_MRG }}"
    subscription_id: "{{ AKS_SUB }}"
  register: vnetinfo

- set_fact:
    jq_name: "[?contains(name, 'aks')]"
    jq_nic_apps_name: "[?contains(name, 'apps-privatelink-pe')]"
    jq_nic_api_name: "[?contains(name, 'api-privatelink-pe')]"

- set_fact:
    AKS_SUBNET: "{{ vnetinfo.virtualnetworks[0].subnets | json_query(jq_name) | first }}"
    AKS_VNET: "{{ vnetinfo.virtualnetworks[0].name }}"

- name: Get private-link-services map
  command: |-
    az network private-link-service list --subscription '{{ HUB_SUB }}' --output json
  register: privatelink_map

- set_fact:
    HUB_PRIVATE_LINK_MAP: "{{ privatelink_map.stdout | from_json | json_query('[*].{name: name, id: id}') }}"

- name: Get network interfaces within a resource group
  azure.azcollection.azure_rm_networkinterface_info:
    resource_group: "{{ AKS_MRG }}"
    subscription_id: "{{ AKS_SUB }}"
  register: NIC_MAP

- set_fact:
    NIC_APPS: "{{ NIC_MAP.networkinterfaces | json_query(jq_nic_apps_name) }}"
    NIC_API: "{{ NIC_MAP.networkinterfaces | json_query(jq_nic_api_name) }}"

- name: ensure an "A" record set with multiple records - *.apps
  azure.azcollection.azure_rm_privatednsrecordset:
    resource_group: "{{ AKS_MRG }}"
    relative_name: "*.apps"
    subscription_id: "{{ AKS_SUB }}"
    zone_name: "{{ HUB_PDNSZ }}"
    record_type: A
    records:
      - entry: "{{ item.ip_configurations[0].private_ip_address }}"
    state: absent
  with_items:
    - "{{ NIC_APPS }}"
  ignore_errors: true

- name: ensure an "A" record set with multiple records - api
  azure.azcollection.azure_rm_privatednsrecordset:
    resource_group: "{{ AKS_MRG }}"
    relative_name: "api"
    subscription_id: "{{ AKS_SUB }}"
    zone_name: "{{ HUB_PDNSZ }}"
    record_type: A
    records:
      - entry: "{{ item.ip_configurations[0].private_ip_address }}"
    state: absent
  with_items:
    - "{{ NIC_API }}"
  ignore_errors: true

- name: ensure an "A" record set with multiple records - api-int
  azure.azcollection.azure_rm_privatednsrecordset:
    resource_group: "{{ AKS_MRG }}"
    relative_name: "api-int"
    subscription_id: "{{ AKS_SUB }}"
    zone_name: "{{ HUB_PDNSZ }}"
    record_type: A
    records:
      - entry: "{{ item.ip_configurations[0].private_ip_address }}"
    state: absent
  with_items:
    - "{{ NIC_API }}"
  ignore_errors: true

- name: Create private endpoint connected to private link
  azure.azcollection.azure_rm_privateendpoint:
    name: "{{ item.name }}-pe"
    resource_group: "{{ AKS_MRG }}"
    subscription_id: "{{ AKS_SUB }}"
    private_link_service_connections:
      - name: "{{ item.name }}-cn"
        private_link_service_id: "{{ item.id }}"
    subnet:
      id: "{{ AKS_SUBNET.id }}"
    tags:
      owner: "acm"
    state: absent
  with_items: "{{ HUB_PRIVATE_LINK_MAP }}"
  ignore_errors: true

- name: Delete a virtual network link
  azure.azcollection.azure_rm_privatednszonelink:
    resource_group: "{{ AKS_MRG }}"
    name: "{{ HUB_PDNSZ }}-link"
    zone_name: "{{ HUB_PDNSZ }}"
    virtual_network: "{{ AKS_VNET }}"
    subscription_id: "{{ AKS_SUB }}"
    registration_enabled: yes
    state: absent
    tags:
      owner: "acm"

- name: Delete private dns zone
  azure.azcollection.azure_rm_privatednszone:
    resource_group: "{{ AKS_MRG }}"
    name: "{{ HUB_PDNSZ }}"
    subscription_id: "{{ AKS_SUB }}"
    state: absent
    tags:
      owner: "acm"
