# general
phase_name: "RHAAP"
# ocp setup
cluster_name: "acm5"
azure_resource_group: "rg-acm"
azure_cluster_resource_group: "rg-acm-cluster"
azure_location: "eastus"
azure_dns_root: na.mgmt.ansiblecloud.com
azure_dns_zone: "na.mgmt.ansiblecloud.com"
master_instance_type: "Standard_D4ds_v5"
worker_instance_type: "Standard_D8ds_v5"
# AAP setup
controller_host: "https://controller.dev.mgmt.ansiblecloud.com"
inventory_source_name: "azure-rhaap"
vault_uri: "https://kv-acm-sre-rhaap.vault.azure.net"
# ArgoCD
argocd_env: "prod"
# Additional public DNS Setup
parent_dns_zone: "na.mgmt.ansiblecloud.com"
parent_dns_zone_resource_group: "rg-core-infrastructure" # RG for parent public DNS zone
