apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- catalogsource.yaml
- operatorgroup.yaml
- subscription.yaml
- idpconfig.yaml
- managedclusterset.yaml
- placement.yaml
- managedclustersetbinding.yaml
